Repository jsonnet-libs/k8s, pull requests merged in 2021-12, with the labels that each got.

#97 Fix CRD Kind naming + documentation generation
  go.sum
  pkg/model/gvk.go
  pkg/model/load.go
  pkg/render/render.go
Labels: kind/bug-fix, kind/enhancement

#102 Add Cluster API + AWS Provider templates, improve applying CRDs on generation step
  .github/workflows/main.yml
  README.md
  libs/cluster-api-provider-aws/config.jsonnet
  libs/cluster-api/config.jsonnet
  scripts/gen.sh
Labels: kind/enhancement, kind/crd-extension

#83 Support null on builder
  pkg/builder/marshal.go
  pkg/builder/objects_test.go
  pkg/builder/primitives.go
Labels: question, contributor/waiting-for-corrections
